### ISSUE TITLE
Crazy games and Poki not working

### ISSUE THREAD

**Issue by Hahhahahahahaahah** [molangning/bypass#1]

**Comment by molangning** [comment]
hello, can you please give me more details so that I can work out the issue?

**Comment by Hahhahahahahaahah** [comment]
![image](https://github.com/molangning/bypass/assets/140124294/c10b4cda-ae00-4958-bfe6-573d6dc9a3f1)
![image](https://github.com/molangning/bypass/assets/140124294/3ca3a0c7-9b55-4671-9819-59ba1ecb7d03)

**Comment by Hahhahahahahaahah** [comment]
After I click a game I am stuck on a black page

**Comment by molangning** [comment]
![IMG_20230721_124435](https://github.com/molangning/bypass/assets/133737702/493b6024-2fac-4075-91ce-e7ff942750ff)
I am unable to reproduce this issue, can you take a recording?

**Comment by Hahhahahahahaahah** [comment]
Do you have an email that i can send to?

**Comment by Hahhahahahahaahah** [comment]
Great work on doing the bypass btw

**Comment by molangning** [comment]
thank you! you can reach me at emailproxy1423@duck.com
do let me know if the email does not work.

**Comment by molangning** [comment]
hello, can you resend the file to mo_langning@students.edu.sg? the file is too big to download

**Comment by Hahhahahahahaahah** [comment]
https://drive.google.com/file/d/14LsMqqG9mblfAdIP7u9LxiBBZHu1qLaC/view?usp=drivesdk

**Comment by molangning** [comment]
can you use your hotspot and try and reproduce this issue? currently the games are still playable.

**Comment by molangning** [comment]
hello, is it working now?

**Comment by molangning** [comment]
this issue cannot be replicated, please reopen the issue if it persists
