### ISSUE TITLE
Restricted 

### ISSUE THREAD

**Issue by Idlycg** [molangning/bypass#10]
![IMG_5027](https://github.com/molangning/bypass/assets/132731035/e1d57a54-4d1b-4a8f-b8e8-80917535fda2)

**Comment by molangning** [comment]
how
can you try revisiting the page?

**Comment by molangning** [comment]
![IMG_0484](https://github.com/molangning/bypass/assets/133737702/b75d4a21-3e84-4072-958a-c9d9a191d714)
it works on my end.
what is your school?

**Comment by Idlycg** [comment]
CCSS

**Comment by molangning** [comment]
does reloading the page fix the issue?

**Comment by Idlycg** [comment]
Nope

**Comment by Idlycg** [comment]
Got any email that I could send to?
the recording

**Comment by molangning** [comment]
sure, you can send it to mo_langning@students.edu.sg

**Comment by Idlycg** [comment]
Sent

**Comment by Idlycg** [comment]
Mine is idlycg@gmail.com

**Comment by molangning** [comment]
I will look into it as soon as I can, right after amath
do you want another mirror in the meantime?

**Comment by Idlycg** [comment]
Sure

**Comment by molangning** [comment]
I will email you a personal mirror, share it at your own risk

**Comment by Idlycg** [comment]
Ok
👍
Thank u

**Comment by molangning** [comment]
welcome :)

**Comment by molangning** [comment]
you should see it soon

**Comment by molangning** [comment]
So I just saw the video, and what may have happened is that mobile guardian caught the temporary redirect as a bypass and blocked it. Can you copy and paste the link in a new tab?

**Comment by Idlycg** [comment]
Nope

**Comment by molangning** [comment]
worth a try ig

**Comment by molangning** [comment]
I may need some help in writing documentation for self deployment, can you help me?

**Comment by Idlycg** [comment]
> 

Can
