### ISSUE TITLE
The redirect 

### ISSUE THREAD

**Issue by SAIBOOO** [molangning/bypass#12]
### **Debug details**
Go to /bypass and paste the content here.

**Describe the bug**
CCSS has restricted the redirector again >:(

**To Reproduce**

**Expected behavior**

**Screenshots**

![9823FCFE-C6E8-4835-BB42-1F38913691F8](https://github.com/molangning/bypass/assets/143177297/8e508695-ea45-4265-8d7d-cc44eea3ec33)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPadOS 16.3.1 (20D67)
 - OS: 16.31
 - Browser: google and safari

**Additional context**
- The school is changkat

**Comment by molangning** [comment]
Hello, these mirrors have been going down lately. Can you give me your email so that I can email you the new link?

**Comment by molangning** [comment]
try the second mirror that I will be posting soon
