### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by Lililiuy** [molangning/bypass#13]
**Debug details**
Go to /bypass and paste the content here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Details about which school you are from if website is restricted.

**Comment by molangning** [comment]
First off, this project isn't meant to work out of the box yet. Some more work is required for that to happen. You did not give any more details other than "deployment issues", which makes it very hard to fix this issue as I need more details.

Please provide me with more details on how you tried to deploy it.

**Comment by dric4** [comment]
There seems to be a typo in the code. Extra bracket in line 51 is the error.

**Comment by molangning** [comment]
I think I fixed the bug, can you try again?(delete repo and try again)

**Comment by dric4** [comment]
Still not working

**Comment by molangning** [comment]
bruh it's Sunday

**Comment by molangning** [comment]
issue has been fixed
