### ISSUE TITLE
Can’t log in to discord

### ISSUE THREAD

**Issue by dric4** [molangning/bypass#26]
After I complete the login it says the site is restricted. When I try to complete the login the process repeats, as I’m still not logged in.

**Comment by dric4** [comment]
Uploading RPReplay_Final1694355495.mp4…

**Comment by dric4** [comment]
https://github.com/molangning/bypass/assets/142514375/326daa46-6b07-4a94-82d7-8a05c9ec50c7

**Comment by molangning** [comment]
Can you try registering on your phone first then using the phone to scan the qr code?

**Comment by Idlycg** [comment]
This happens sometimes, you’ll need to refresh the page first, then close that site and try it again with the redirector

**Comment by molangning** [comment]
did that work? I do not use discord anymore so I can’t replicate that problem

**Comment by Idlycg** [comment]
I had that problem too, but it works

**Comment by Idlycg** [comment]
After I did what I said before

**Comment by molangning** [comment]
okay that’s great, can I close this issue now? @dric4 just follow @Idlycg method
