### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Ry4nGup14** [molangning/bypass#28]
**Is your feature request related to a problem? Please describe.**
Mirror works but still shows as blocked. School is Victoria School.
![Screenshot 2023-09-17 6 22 57 PM](https://github.com/molangning/bypass/assets/145260619/d504387d-0fe6-4e91-80e5-d2243a8f2c61)
![Screenshot 2023-09-17 6 22 57 PM](https://github.com/molangning/bypass/assets/145260619/1b94c0fa-3d17-4cc3-b02b-209136d207d9)

**Describe the solution you'd like**
Fix the mirror or find out the solution. 

**Describe alternatives you've considered**

**Additional context**

**Won't fix/add**
- features that proxy connections, replit does not support this
- multiple redirects (e.g. website redirects you to another link which is restricted, you are surposed to copy and paste the link into the bypass

**Comment by Idlycg** [comment]
Ok, I’ll give you my personal link, what’s your email, (share at ur own risk)

**Comment by Ry4nGup14** [comment]
***@***.***

**Comment by Idlycg** [comment]
bro what
your email is asterisk?

**Comment by Ry4nGup14** [comment]
Huh wdym

**Comment by Idlycg** [comment]
Ok, email me: idlycg@gmail.com

**Comment by molangning** [comment]
did the personal mirror work?

**Comment by Ry4nGup14** [comment]
Still didn't try it yet.

**Comment by Ry4nGup14** [comment]
Not working bro.

[image: image.png]

**Comment by molangning** [comment]
can you try deploying it on your personal replit account?

**Comment by molangning** [comment]
hey, I have just written some self deployment instructions in the wiki. Do let me know if you have any problems with the process

**Comment by Ry4nGup14** [comment]
Wdym

**Comment by molangning** [comment]
https://github.com/molangning/bypass/wiki/Self-hosting-on-replit

**Comment by molangning** [comment]
use the github issue menu too, it’s much more easier

**Comment by Ry4nGup14** [comment]
still dont work

**Comment by molangning** [comment]
can you give me your email so that I can email you the link?

**Comment by Ry4nGup14** [comment]
***@***.***

**Comment by molangning** [comment]
send me an email at emailproxy1423[AT]gmail.com
the email you sent me gets filtered.
just to confirm, no other mirrors work?

**Comment by Ry4nGup14** [comment]
No other mirrors work

**Comment by molangning** [comment]
even this? https://infamousroyalsigns--bdaajfjais.repl.co/bypass

**Comment by Ry4nGup14** [comment]
nope, when i open up a link, it redirects me to a new tab and then it shows
blocked

**Comment by molangning** [comment]
can you access this? https://tic-tac-toe-live.coder-301.repl.co/
your school may have blocked *.repl.co 
copy and paste this url into your browser

**Comment by Ry4nGup14** [comment]
Yes i can access it

**Comment by Ry4nGup14** [comment]
it showsme this tho for the second link

[image: image.png]

**Comment by molangning** [comment]
can you please go to github.com and reupload the image?
https://github.com/molangning/bypass/issues/28

**Comment by molangning** [comment]
closed to inactivity
