### ISSUE TITLE
Blocked.

### ISSUE THREAD

**Issue by Idlycg** [molangning/bypass#33]
Some one from St Patrick can’t access the redirector and they can’t visit repl.co

![image](https://github.com/molangning/bypass/assets/132731035/826dc097-fa61-4253-9431-c4b15790e908)

**Comment by molangning** [comment]
Is it possible to use the other mirrors?

**Comment by Idlycg** [comment]
Nope.

**Comment by molangning** [comment]
are all repl.co website blocked?

**Comment by molangning** [comment]
Are you sure that link 6 - 10 are blocked?

**Comment by Idlycg** [comment]
yes to both

**Comment by molangning** [comment]
I got a different mirror that should work, can you see if you can contact him to get the mirror?

**Comment by molangning** [comment]
different mirror doesn't work, something to do with the way header information is handled.

**Comment by molangning** [comment]
guys I am running out of free places to host this that won't get block IJWHF;OHBOFoho

**Comment by molangning** [comment]
I found a working mirror but it requires a bit more technical setup and have a 50 hours per month runtime fee. Is your friend okay with this?

**Comment by Idlycg** [comment]
I’ll ask first

**Comment by molangning** [comment]
ok ty

**Comment by molangning** [comment]
one more thing: I just noticed that your friend has an extension that enforces the block. Does deleting the extension file work?

**Comment by Idlycg** [comment]
Hold on, i try find a free hosting website

**Comment by Idlycg** [comment]
I ask him if can

**Comment by molangning** [comment]
> Hold on, i try find a free hosting website

I am currently porting the code to nodeJS, so that I can host it on more sites. If you find any more sites send me the link through my email

**Comment by Idlycg** [comment]
ok

**Comment by molangning** [comment]
I ported the bare minimum of it, but it should be more stealthy
tell your friend to email me for the new link

**Comment by Idlycg** [comment]
> I ported the bare minimum of it, but it should be more stealthy
> tell your friend to email me for the new link

k

**Comment by Idlycg** [comment]
ok sent

**Comment by molangning** [comment]
https://learned-plausible-salesman.glitch.me/3tanzqzpibl/

tell me if not working, try not to use it
