### ISSUE TITLE
Bypass fail.

### ISSUE THREAD

**Issue by ghost** [molangning/bypass#40]
**Debug details**
Go to /debug and paste the content here.
`timezone:%20Asia/Hong_Kong%0Auuid:%20uuid_a1753bbeb2e5d8e3553ffbbf3ec6c0e3%0Atime%20generated:1699937901`

**Describe the bug**
Bypass fail.

**Expected behavior**
Able to go to instagram.

**Screenshots**
![IMG_2011](https://github.com/molangning/bypass/assets/106787899/bac9de03-5b4f-4a94-9c5c-2a6fa993e2dd)

**Desktop (please complete the following information):**
 - iPadOS 17.1
 - Safari

**Additional context**
- I am thinking of that, you could attempt try encrypt the url.
![IMG_2012](https://github.com/molangning/bypass/assets/106787899/89040818-852d-4c3b-b8fb-080958d157c0)

**Comment by ghost** [comment]
Currently, the `www.instagram.com` is detected and blocked. I am thinking of that you might try to encrypt the url of `www.instagram.com`.

**Comment by molangning** [comment]
Currently there is no workaround for this, and encryption of the url is impossible as the redirect location needs to be able to be accessed by the browser itself and thus it's censor. You can try other social media websites or frontends like bilblogram

**Comment by molangning** [comment]
Can I close this issue now? There is no way for me to help you unless you can elaborate on what you meant by "encrypting" the url
