### ISSUE TITLE
Add to home screen feature

### ISSUE THREAD

**Issue by dric4** [molangning/bypass#44]
Will it be possible to make the bypasser be added to homescreen to become an app. I know this is possible on certain websites but can this be done here? Basically can you turn this into a PWA.

**Comment by molangning** [comment]
That is *somewhere* on my todo list, but I am not sure on how to actually implement it. Do you

1. Want the pwa to open it in your browser?
2. Open it in the same tab as the broweser?

If you have any example of pwa please post it here.

**Comment by dric4** [comment]
I would like it to open as a seperate page that acts something like an app. Like it can be added to Home Screen and open websites. Ive gotten it to work so it’s fine. I used save-as.app to add it

**Comment by molangning** [comment]
Alr, thanks for taking the time to open this issue.
