### ISSUE TITLE
Redirector seems inconsistent?

### ISSUE THREAD

**Issue by dric4** [molangning/bypass#45]
![IMG_0300](https://github.com/molangning/bypass/assets/142514375/c9579003-42c7-4b88-b549-3ea8a128c41c)
I often get this error when I use the redirector sometimes. It’s not all the time but it happens occasionally.

**Comment by molangning** [comment]
Copy and paste the url here

**Comment by dric4** [comment]
https://working-enormous-aardwolf.glitch.me/4k0ab91gk3n/

**Comment by molangning** [comment]
What about the url with the too many redirects one?

**Comment by molangning** [comment]
Hi can I close this? @dric4

**Comment by Idlycg** [comment]
It is your schoo, wifi side, not the redirector
