### ISSUE TITLE
Access Restricted now :(

### ISSUE THREAD

**Issue by Idlycg** [molangning/bypass#5]
Idk what happened
![IMG_4996](https://github.com/molangning/bypass/assets/132731035/20cbfd17-8347-48ef-a440-e6dd35dad1e8)
 but it says access restricted:

**Comment by Idlycg** [comment]
I suggest making a new website with the same code.

**Comment by dric4** [comment]
Please fix this :( I was using this heavily on my pld

**Comment by molangning** [comment]
Fix will be soon, I will post a mirror here

**Comment by molangning** [comment]
btw guys, which schools are you from? It seems like more people from all over singapore are using this tool

**Comment by molangning** [comment]
> Please fix this :( I was using this heavily on my pld

It should be fixed now, I hosted it on another replit url. Can you go and check it?

**Comment by dric4** [comment]
I’m from RI

**Comment by Idlycg** [comment]
I’m from CCSS

**Comment by Idlycg** [comment]
> btw guys, which schools are you from? It seems like more people from all over singapore are using this tool

I showed it to my friends too

**Comment by molangning** [comment]
that’s great :)
how did you guys find out about this?

**Comment by dric4** [comment]
Just from google lol

**Comment by molangning** [comment]
oh lol what search terms did you use?

**Comment by Idlycg** [comment]
how to bypass mobile guardian

**Comment by Idlycg** [comment]
Also the bypasser can work in google chrome, I have tested it

**Comment by molangning** [comment]
> how to bypass mobile guardian

bruh

any other keywords that I can put inside the page?

**Comment by molangning** [comment]
> Also the bypasser can work in google chrome, I have tested it

of course it works, it is a redirect issuer

**Comment by molangning** [comment]
I’m gonna close this issue because I resolved it, have a great day everyone 😄
