### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by sgbusntrain** [molangning/bypass#6]
I would like to suggest to remove poki as a shortcut as it does not work and replace it with instagram

**Comment by molangning** [comment]
instagram does not work on my side, can you try typing in the url manually and trying to sign in?

**Comment by Idlycg** [comment]
Instagram works but poki does not

**Comment by molangning** [comment]
okay, but some devices still works. I will just put instagram next to discord for now

**Comment by molangning** [comment]
done
